// <auto-generated />
using System;
using Hamburgerz.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Hamburgerz.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260513125748_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Hamburgerz.Models.AnalysisCache", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .HasColumnType("longtext")
                        .HasColumnName("content");

                    b.Property<DateTime>("GeneratedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("generated_at");

                    b.Property<int>("MeasurementCount")
                        .HasColumnType("int")
                        .HasColumnName("measurement_count");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("status");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("analysis_cache");
                });

            modelBuilder.Entity("Hamburgerz.Models.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("countries");
                });

            modelBuilder.Entity("Hamburgerz.Models.CountryEN", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("countriesen");
                });

            modelBuilder.Entity("Hamburgerz.Models.EmailVerificationToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("expires_at");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("token");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.ToTable("email_verification_tokens");
                });

            modelBuilder.Entity("Hamburgerz.Models.PasswordResetToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("expires_at");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("token");

                    b.Property<bool>("Used")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("used");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.ToTable("password_reset_tokens");
                });

            modelBuilder.Entity("Hamburgerz.Models.RiskData", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID"));

                    b.Property<float>("BurnoutRisk")
                        .HasColumnType("float")
                        .HasColumnName("burnout_risk");

                    b.Property<string>("CompanySize")
                        .HasColumnType("longtext")
                        .HasColumnName("company_size");

                    b.Property<int?>("DisconnectScore")
                        .HasColumnType("int")
                        .HasColumnName("disconnect_score");

                    b.Property<float>("ExerciseHours")
                        .HasColumnType("float")
                        .HasColumnName("exercise_hours");

                    b.Property<int?>("ExperienceYears")
                        .HasColumnType("int")
                        .HasColumnName("experience_years");

                    b.Property<int?>("FocusScore")
                        .HasColumnType("int")
                        .HasColumnName("focus_score");

                    b.Property<string>("Gender")
                        .HasColumnType("longtext")
                        .HasColumnName("gender");

                    b.Property<int>("InternetSpeed")
                        .HasColumnType("int")
                        .HasColumnName("internet_speed");

                    b.Property<string>("JobRole")
                        .HasColumnType("longtext")
                        .HasColumnName("job_role");

                    b.Property<int>("MeetingsPerDay")
                        .HasColumnType("int")
                        .HasColumnName("meetings_per_day");

                    b.Property<int?>("MoodScore")
                        .HasColumnType("int")
                        .HasColumnName("mood_score");

                    b.Property<int>("ProductivityScore")
                        .HasColumnType("int")
                        .HasColumnName("productivity_score");

                    b.Property<float>("ScreenTime")
                        .HasColumnType("float")
                        .HasColumnName("screen_time");

                    b.Property<float>("SleepHours")
                        .HasColumnType("float")
                        .HasColumnName("sleep_hours");

                    b.Property<string>("StressLevel")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("stress_level");

                    b.Property<string>("Suggestion")
                        .HasColumnType("longtext")
                        .HasColumnName("suggestion");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("Time_stamp");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("fk_userID");

                    b.Property<string>("WorkEnvironment")
                        .HasColumnType("longtext")
                        .HasColumnName("work_environment");

                    b.Property<float>("WorkHours")
                        .HasColumnType("float")
                        .HasColumnName("work_hours");

                    b.HasKey("ID");

                    b.HasIndex("UserId");

                    b.ToTable("riskdata");
                });

            modelBuilder.Entity("Hamburgerz.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("date")
                        .HasColumnName("birth_date");

                    b.Property<string>("CompanySize")
                        .HasColumnType("longtext")
                        .HasColumnName("company_size");

                    b.Property<int?>("CountryID")
                        .HasColumnType("int")
                        .HasColumnName("countryid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("email");

                    b.Property<int?>("ExperienceYears")
                        .HasColumnType("int")
                        .HasColumnName("experience_years");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("gender");

                    b.Property<bool>("IsEmailVerified")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_email_verified");

                    b.Property<string>("JobRole")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("job_role");

                    b.Property<string>("PasswordHashed")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("password_hashed");

                    b.Property<byte[]>("ProfileImage")
                        .HasColumnType("longblob")
                        .HasColumnName("profile_image");

                    b.Property<string>("ProfileImageType")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("profile_image_type");

                    b.Property<string>("UserType")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("user_type");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("username");

                    b.Property<string>("WorkEnvironment")
                        .HasColumnType("longtext")
                        .HasColumnName("work_environment");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("users");
                });

            modelBuilder.Entity("Hamburgerz.Models.RiskData", b =>
                {
                    b.HasOne("Hamburgerz.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
